# Parameters:
#   SecurityGroupDescription:
#     Description: SecurityGroupDescription
#     Type: String
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-057752b3f1d6c4d6c
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: cloudformation19
      KeyName: cloudformation
      SecurityGroups:
        - !Ref SecurityGroupMu1
      UserData:
        Fn::Base64: 
          !Sub 
            - |
              #!/bin/bash
              sudo yum update -y 
              sudo yum install docker -y
              sudo systemctl start docker
              sudo systemctl enable docker
              docker pull techhouse1901/dockerdoc:latest
              docker run -d -p 8080:8080 -p 8443:8443 techhouse1901/dockerdoc
              mkdir /home/ec2-user/${DirName}
            - { DirName: !Join [ '-', [ !Ref AWS::StackName, !Ref AWS::Region, 'customdir' ] ] }
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance
  SecurityGroupMu1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Replace with the desired CIDR range
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Replace with the desired CIDR range
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        
aws cloudformation create-stack --stack-name jenkins --template-body file://ec2-instance.yaml --parameters ParameterKey=SecurityGroupDescription,ParameterValue="create multiple inbound rule"


pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control
                // For example, using Git
                git 'https://github.com/your-repo.git'
            }
        }

        stage('Deploy Stack') {
            steps {
                script {
                    def stackName = 'YourStackName'
                    def templateFile = 'path/to/your/cloudformation-template.yaml'
                    def awsRegion = 'us-west-2' // Replace with your desired AWS region

                    // Install and configure AWS CLI
                    sh 'pip install awscli'
                    sh 'aws configure set aws_access_key_id <YOUR_ACCESS_KEY>'
                    sh 'aws configure set aws_secret_access_key <YOUR_SECRET_ACCESS_KEY>'
                    sh "aws configure set default.region $awsRegion"

                    // Validate CloudFormation template
                    sh "aws cloudformation validate-template --template-body file://$templateFile"

                    // Create or update the CloudFormation stack
                    sh "aws cloudformation deploy --stack-name $stackName --template-file $templateFile --capabilities CAPABILITY_IAM"
                }
            }
        }
    }
}
